// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwxrV-9k-99arnGEIk2QWSiLTHN7FYn9Q',
    appId: '1:977924980282:web:0d43e903b76096de57ff03',
    messagingSenderId: '977924980282',
    projectId: 'travelling-app-8cb49',
    authDomain: 'travelling-app-8cb49.firebaseapp.com',
    storageBucket: 'travelling-app-8cb49.appspot.com',
    measurementId: 'G-ZCVP10CM21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUCd1ZZ8rBGMlCvU1Gwqt1dS_UZqcrOI',
    appId: '1:977924980282:android:3f3a3ddca910cb6557ff03',
    messagingSenderId: '977924980282',
    projectId: 'travelling-app-8cb49',
    storageBucket: 'travelling-app-8cb49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHaoOivX1Ck85zszcIlK3D7XdZ-oCzeAA',
    appId: '1:977924980282:ios:3765ea41e66ba11e57ff03',
    messagingSenderId: '977924980282',
    projectId: 'travelling-app-8cb49',
    storageBucket: 'travelling-app-8cb49.appspot.com',
    iosBundleId: 'com.example.travellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHaoOivX1Ck85zszcIlK3D7XdZ-oCzeAA',
    appId: '1:977924980282:ios:3765ea41e66ba11e57ff03',
    messagingSenderId: '977924980282',
    projectId: 'travelling-app-8cb49',
    storageBucket: 'travelling-app-8cb49.appspot.com',
    iosBundleId: 'com.example.travellingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwxrV-9k-99arnGEIk2QWSiLTHN7FYn9Q',
    appId: '1:977924980282:web:cab830c47778316357ff03',
    messagingSenderId: '977924980282',
    projectId: 'travelling-app-8cb49',
    authDomain: 'travelling-app-8cb49.firebaseapp.com',
    storageBucket: 'travelling-app-8cb49.appspot.com',
    measurementId: 'G-FHQDZDNG7N',
  );

}